services:
  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/backend
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      DATABASE_URL: ${FLASK_SQLALCHEMY_DATABASE_URI}  # Set DATABASE_URL here
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: >
      bash -c "flask db upgrade && flask run -h 0.0.0.0"
    depends_on:
    - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - db_data:/var/lib/postgresql/data    
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
    - 8000:8000
volumes:
  db_data: