"""Create roommate expenses table

Revision ID: 187e756c1069
Revises: 829d20a24b3a
Create Date: 2025-02-06 15:23:12.856425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187e756c1069'
down_revision = '829d20a24b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roommate_expenses',
    sa.Column('expense_fkey', sa.Integer(), nullable=False),
    sa.Column('roommate_fkey', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['expense_fkey'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['roommate_fkey'], ['roommates.id'], ),
    sa.PrimaryKeyConstraint('expense_fkey', 'roommate_fkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roommate_expenses')
    # ### end Alembic commands ###
