"""Add end_date and recurrence to Chore model

Revision ID: 2dcfa885243b
Revises: 35c728a33cf1
Create Date: 2025-02-25 04:26:44.471954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcfa885243b'
down_revision = '35c728a33cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('recurrence', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('recurrence')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
