"""Update Roommate model: add firstName, lastName, username, password_hash

Revision ID: 35c728a33cf1
Revises: ce6050036851
Create Date: 2025-02-20 01:58:55.914899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c728a33cf1'
down_revision = 'ce6050036851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_periods', schema=None) as batch_op:
        batch_op.alter_column('room_fkey',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('roommates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roommates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('expense_periods', schema=None) as batch_op:
        batch_op.alter_column('room_fkey',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
