"""Remove duration column from Chore model

Revision ID: 3d3a81b9395c
Revises: a967338b4328
Create Date: 2025-02-25 19:05:58.377159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d3a81b9395c'
down_revision = 'a967338b4328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
