"""Create roommate table

Revision ID: 3fe0fcd18f8f
Revises: 7bc020ad8c0d
Create Date: 2025-02-06 15:01:33.572282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe0fcd18f8f'
down_revision = '7bc020ad8c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roommates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_fkey', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_fkey'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roommates')
    # ### end Alembic commands ###
