"""Add is_read field to notifications

Revision ID: 6ebdc67f9a78
Revises: 7d0d3826dd60
Create Date: 2025-03-09 23:26:37.359773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '6ebdc67f9a78'
down_revision = '7d0d3826dd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
    
    # Update existing rows to set is_read to False
    op.execute(text("UPDATE notifications SET is_read = FALSE"))
    
    # Now make the column NOT NULL
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
