"""Create expense table

Revision ID: 829d20a24b3a
Revises: 3fe0fcd18f8f
Create Date: 2025-02-06 15:13:37.398478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829d20a24b3a'
down_revision = '3fe0fcd18f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cost', sa.Double(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('room_fkey', sa.Integer(), nullable=False),
    sa.Column('roommate_fkey', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_fkey'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['roommate_fkey'], ['roommates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
