"""Create chores table

Revision ID: 909fe4f32d46
Revises: 187e756c1069
Create Date: 2025-02-10 16:54:28.743397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909fe4f32d46'
down_revision = '187e756c1069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('autorotate', sa.Boolean(), nullable=False),
    sa.Column('is_task', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assignee_fkey', sa.Integer(), nullable=False),
    sa.Column('assignor_fkey', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_fkey'], ['roommates.id'], ),
    sa.ForeignKeyConstraint(['assignor_fkey'], ['roommates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chores')
    # ### end Alembic commands ###
