"""Add profile picture to roommate model

Revision ID: 9a1c23d80797
Revises: e3c906c4907f
Create Date: 2025-03-03 04:11:42.558446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1c23d80797'
down_revision = 'e3c906c4907f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roommates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roommates', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
