"""Added expense_period foreign key for expense

Revision ID: b589cfba4c0f
Revises: 35c728a33cf1
Create Date: 2025-02-22 17:18:09.083834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b589cfba4c0f'
down_revision = '35c728a33cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_period_fkey', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'expense_periods', ['expense_period_fkey'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_period_fkey')

    op.create_table('test',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
