"""Remove autorotate field from chores table

Revision ID: b646d2b2d43d
Revises: e3c906c4907f
Create Date: 2025-03-04 18:27:07.461756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b646d2b2d43d'
down_revision = 'e3c906c4907f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('autorotate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autorotate', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
