"""Added expense_period foreign key to expense

Revision ID: e3c906c4907f
Revises: 3d3a81b9395c
Create Date: 2025-02-27 05:48:23.436056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c906c4907f'
down_revision = '3d3a81b9395c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_period_fkey', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'expense_periods', ['expense_period_fkey'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_period_fkey')

    # ### end Alembic commands ###
