"""Add rotation_order to chores

Revision ID: ffb4c21d9d23
Revises: b646d2b2d43d
Create Date: 2025-03-04 19:07:15.165267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffb4c21d9d23'
down_revision = 'b646d2b2d43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_order', postgresql.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('rotation_order')

    # ### end Alembic commands ###
